### ISSUE TITLE
Does not build with ldc

### ISSUE THREAD

**Issue by rnleach** [etcimon/windows-headers#2] opened 2016-11-15 01:39 UTC
Building project with ldc2 and dub, it errors on "winuser.d (4400): Error: Function type does not match previously declared function with the same mangled name: GetMonitorInfoA"

Looking at the file, it seems there are overloads of the function with the LPMONITORINFO and LPMONITORINFOEX structures. Which is weird, because I didn't think you could overload functions in C! I'm guessing this works with DMD because it mangles the names without regard to the arguments, or it just doesn't check for conflicting declarations of `extern (C)` functions. I'm not sure if this is a bug in LDC, DMD, or this library.

Looking online I found a Winuser.h file, and it only listed one version of the function that used the LPMONITORINFO structure. But the windows documentation lists the function as being able to take either structure as an argument. I'm confused how you could even get the function to compile with the 'ex' structure unless you use a cast in C!

**Comment by etcimon** [comment] 2016-11-15 01:47
I think I hadn't stumbled on this one because I generally use in dub: "versions-windows": ["WindowsVista", "Unicode"],

This seems to be a redundant definition, you're right. Also, interesting to see this done differently here: https://github.com/dlang/druntime/blob/master/src/core/sys/windows/winuser.d#L4426

**Comment by rnleach** [comment] 2016-11-15 02:13
I just found the winuser.h file on my local machine from the windows 8.1 SDK. I see it has a pre-processor definition where it only defines the EX struct `#ifdef __cplusplus`. So I guess there really isn't an overloading issue in C.

**Comment by rnleach** [comment] 2016-11-15 02:21
I thought this package was more up to data and complete than `core.sys.windows`, but looking in there now it seems pretty complete now. Is there still a difference?

**Comment by etcimon** [comment] 2016-11-15 02:27
There are some differences regarding the recent commits in this library. I also prefer keeping control over the headers in order to add/remove missing definitions without having to require/use a more recent version of druntime.

**Comment by dkorpel** [comment] 2018-11-21 15:12
I just noticed that my [issue 5](https://github.com/etcimon/windows-headers/issues/5) is a duplicate of this issue, so this one can be closed now as well.

**Closed as completed** 2018-11-21 16:45 UTC
